name: Sync Angular Lib to Public Repo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'libs/bluecrow-angular/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Subtree to Public Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUBLIC_REPO_TOKEN }}
        with:
          source-directory: 'libs/bluecrow-angular'
          destination-github-username: 'sxthumb'
          destination-repository-name: 'bluecrow-angular'
          user-email: 'sxthumb@users.noreply.github.com'
          target-branch: 'main'
